apiVersion: cncp.nl/v1beta1
kind: Tagger
metadata:
  name: example-tagger
  namespace: default
spec:
  labels:
    - key: "customer"
      value: "my-customer-a"
    - key: "env"
      value: "development"
  annotations:
    - key: "customer"
      value: "my-customer-a"
  excludeList:
    - "kube-system"
    - "monitoring"