apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taggers.cncp.nl
spec:
  group: cncp.nl
  names:
    kind: Tagger
    plural: taggers
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
            spec:
              type: object
              properties:
                labels:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                annotations:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                excludeList:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                succeeded:
                  type: boolean
                tagged:
                  type: array
                  items:
                    type: string
          required:
            - spec
      served: true
      storage: true
      subresources:
        # status enables the status subresource.
        status: {}